version: "3.5"
services:
 gatekeeper:
    image: define42/codeservergateway
    ports:
      - 8000:80
      - 443:443
    environment:
      #      SERVER_DOMAIN: code.
      #      ACME_SERVER: https://acme-v02.api.letsencrypt.org/directory
      #      PROXY_DOMAIN: code.
      BASE_DN: "dc=glauth,dc=com"
      BIND_PASSWORD: "mysecret"
      BIND_USER: "cn=serviceuser,ou=svcaccts,dc=glauth,dc=com"
      LDAP_SERVER: "ldapserver:389"
      LDAP_USER_DOMAIN: "example.com"
      HASH_SALT: "123456789"
      CODE_SERVER_IMAGE: "lscr.io/linuxserver/code-server:latest"
      DOCKER_MODS: define42/mods-vim|define42/mods-ca|linuxserver/mods:universal-docker-in-docker|linuxserver/mods:code-server-golang|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-java11
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /data/:/data/
    networks:
      codeserver:
 ldapserver:
    image: define42/ldap
    networks:
      codeserver:
networks:
  codeserver:
    driver: bridge
    name: codeservernetwork
    ipam:
     config:
       - subnet: 10.0.0.0/24
